### PR TITLE
Update Puppeteer and add Windows testing on Travis

### LINKED ISSUE #154: puppeteer unable to launch Chrome on Windows
When using grunt-contrib-qunit on Travis CI with `os: windows`, it fails as follows:

```
>> There was an error with headless chrome
Fatal error: Failed to launch chrome!
[1228/225004.858:ERROR:main_dll_loader_win.cc(134)] Failed to load Chrome DLL from  node_modules\puppeteer\.local-chromium\win64-588429\chrome-win32\chrome.dll: The specified module could not be found. (0x7E)
```

I first encountered this when working on a commit that adds `os: windows` to the Travis CI build matrix of upstream qunitjs/qunit. But I was also able to reproduce it for this repository, at <https://travis-ci.com/Krinkle/grunt-contrib-qunit/jobs/167451645>.

Related reports}:
* <https://bugs.chromium.org/p/chromium/issues/detail?id=873097>
* <https://travis-ci.community/t/puppeteer-not-working-on-windows-container/354>

### PR DESCRIPTION
**Pull request by Krinkle**
Fixes #154.

/cc @XhmikosR

### CODE REVIEW

**Comment by XhmikosR** [comment]
@vladikoff I don't see why you merged this when AppVeyor is also present.

**Comment by vladikoff** [comment]
@XhmikosR we can give it a try and remove it later, no big deal.

**Comment by Krinkle** [comment]
@XhmikosR AppVeyor is great, but I think some users of grunt-contrib-qunit will prefer to use only one CI system and might pick Travis for testing Windows if they are already familiar with that.

Per https://github.com/gruntjs/grunt-contrib-qunit/issues/154, the problem with Chrome only affected Windows Server 2016 (used at Travis), it did not affect AppVeyor (which currently uses Windows Server 2012, I think).

The AppVeyor tests for grunt-contrib-qunit, as well as the AppVeyor tests for qunitjs/qunit were passing. The easiest way to ensure that grunt-contrib-qunit stays green for Windows on Travis, was to add a test for exactly that :)

If AppVeyor can be configured to test both Windows versions, then that would also cover it. But, I do not know AppVeyor well enough to know how to do that.

**Comment by XhmikosR** [comment]
I don't really care which is used as long as only one is used.

**Pull request merged**
