### PR TITLE
feat(headless-chrome): use headless chrome instead of phantomjs

### PR DESCRIPTION
**Pull request by zachelrath**
# Issues Addressed
- #143 

# Summary of Changes
- Switches to running QUnit tests using headless Chrome, utilizing the Puppeteer library

### CODE REVIEW

**Comment by vladikoff** [comment]
@zachelrath Will take a look at this, thanks!

**Comment by zachelrath** [comment]
@vladikoff Any thoughts on the PR?

**Comment by zachelrath** [comment]
@vladikoff Thanks! What is the process for getting a new release published on NPM?

**Comment by vladikoff** [comment]
it's on npm now

**Pull request merged**
