### PR TITLE
Upgrade qunitjs to 2.x

### LINKED ISSUE #122: Upgrade qunitjs to 2.x
As of this writing, `qunitjs@2.0.0-rc1` is available.
The new major version introduces breaking changes across the board, see [migration guide](http://qunitjs.com/upgrade-guide-2.x/).

### PR DESCRIPTION
**Pull request by mucaho**
This is an in-progress implementation that fixes #122 .
- [x] Update bridge between phantomjs and qunit
  - Looks fine, except for [undocumented option](http://api.qunitjs.com/QUnit.config/) `QUnit.config.autorun = false`.  
    It's not mentioned in [upgrade guide](http://qunitjs.com/upgrade-guide-2.x/), so it _should_ continue to work.
- [x] Update tests as stated in upgrade guide
- [x] Change `devDependency` `qunitjs` from version `2.0.0-rc1` to `2.3.0`
- [ ] Update documentation to reflect the change
- [ ] Things I may have missed

### CODE REVIEW

**Comment by jzaefferer** [comment]
Good start, thanks @mucaho!

@leobalter should we add `autorun` to the QUnit.config docs or mention it in the upgrade guide? How should we deal with that here?

**Comment by leobalter** [comment]
autorun is not part of QUnit 2.0. It wasn't a documented feature on 1.x as well. We discussed this on the removals for 2.0

`QUnit.config.autostart` should work and it's documented.

**Comment by jzaefferer** [comment]
@mucaho can you remove/replace any usage of `autorun`?

**Comment by mucaho** [comment]
Ok, removed `autorun`.

However, the test reporter seems to rely on serial execution order of tests. If QUnit will call interleaved callbacks for test cases, that could mess up reporting. (Probably most noticeable with `verbose` set and many asynchronous tests).
Specifically, [`tasks/qunit.js`](https://github.com/gruntjs/grunt-contrib-qunit/blob/461e4082ad5e1e143cc02f28072f7646c721efb5/tasks/qunit.js)`#failedAssertions` ([here](https://github.com/gruntjs/grunt-contrib-qunit/blob/461e4082ad5e1e143cc02f28072f7646c721efb5/tasks/qunit.js#L43-L64), [here](https://github.com/gruntjs/grunt-contrib-qunit/blob/461e4082ad5e1e143cc02f28072f7646c721efb5/tasks/qunit.js#L101), [here](https://github.com/gruntjs/grunt-contrib-qunit/blob/461e4082ad5e1e143cc02f28072f7646c721efb5/tasks/qunit.js#L119), [here](https://github.com/gruntjs/grunt-contrib-qunit/blob/461e4082ad5e1e143cc02f28072f7646c721efb5/tasks/qunit.js#L138)).

One simple approach would be to match the [`QUnit.log`](http://api.qunitjs.com/QUnit.log/) callbacks to the appropriate [`QUnit.testStart`](http://api.qunitjs.com/QUnit.testStart/) & [`QUnit.testDone`](http://api.qunitjs.com/QUnit.testDone/) callbacks by comparing the `name` and `module` fields. However, this may in rare cases not work with asynchronous tests that have the same `name`.

**Comment by jzaefferer** [comment]
You removed the "Run tests serially, not in parallel." comment, is that where you got the idea that something is running in parallel? I'm pretty sure QUnit runs all tests in sequence, not in parallel. Or is there something else?

**Comment by stevenbenner** [comment]
QUnit 2.0.0 has been released and is up on npm now. [2.0.0 release notes](https://github.com/jquery/qunit/blob/2.0.0/History.md)

**Comment by jzaefferer** [comment]
@mucaho could you update this?

**Comment by matzetronic** [comment]
Can you give use

**Comment by Arkni** [comment]
@matzetronic the current version of this plugin (`v1.2.0`) should work just fine with any version of `QUnit`. There is only one requirement of using versions of `QUnit >= 1.23.0` in order to use the CLI flags `--seed` (_not released yet_) and `--modules`.

As for #129, could you please provide the steps + source code to reproduce (please put them in #129)

**Comment by vogdb** [comment]
Hiii! I'm sorry to bother but what is the status here?

**Comment by mucaho** [comment]
Updated the `qunitjs` devDependency to `^2.3.0`.     
Had to adapt the `noglobals` test file since it's no longer possible to overwrite the error reporting function `pushFailure` of QUnit and thus I didn't find a way to prevent QUnit from reporting a failure. If you know of a more elegant workaround, please let me know.

**Comment by leobalter** [comment]
cc @trentmwillis

**Comment by leobalter** [comment]
@Arkni it looks good to me. :shipit:

**Comment by Arkni** [comment]
@mucaho 
Thanks a lot :)

**Comment by mgol** [comment]
@leobalter this plugin needs a major version bump now, doesn't it?

**Comment by trentmwillis** [comment]
Yes, next release should be a major version.

**Comment by leobalter** [comment]
yes, please

**Comment by Arkni** [comment]
We also need to remove this part of code [`phantomjs/bridge.js#L36-L39`](https://github.com/gruntjs/grunt-contrib-qunit/blob/353a7a8b67e5c297d9431420926e50e5ed1995af/phantomjs/bridge.js#L36-L39) before releasing. We don't need that BC check anymore.

**Comment by Arkni** [comment]
@leobalter 
Should we also switch to use the `js-reporter` events instead of the the callback `QUnit.log(...), ...` ?
If we do that, we will need to set the min supported version of `QUnit` to `2.3.0`

**Comment by Arkni** [comment]
OK then. I'll try to remove the lines I referenced in my previous comment https://github.com/gruntjs/grunt-contrib-qunit/pull/123#issuecomment-290749454 and do a release tomorrow.

I'll play with it and test it on some of my projects before changing any thing in this plugin.

Thanks!

**Comment by Arkni** [comment]
Published to npm as `2.0.0` :)

**Pull request merged**
