### PR TITLE
Switch to qunit.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@Arkni: just remember to make this a major version bump :)

**Comment by Arkni** [comment]
I don't think we need to as only a dev-dependency was updated.

**Comment by XhmikosR** [comment]
Yeah, I was mostly talking about the previous changes.

**Comment by Arkni** [comment]
Ah you're right. I will make sure to not forgot this as I also have some changes locally but didn't had the chance to continue working on them.

Thanks for the reminder :)

**Pull request merged**
