### PR TITLE
adding an Introduction to the README

### PR DESCRIPTION
**Pull request by mfrasca**
I'm trying to describe my understanding of the logic, structure and usage of this plugin, hoping it will help others, but also so that next time I have to use it, I will find the `readme` I missed the first time I came here.

### CODE REVIEW

**Comment by Arkni** [comment]
Thanks for your contribution! I'll take a look at it as soon as possible!

**Comment by Arkni** [comment]
Hi @mfrasca 
Finally got some time to review this PR.

All of the `grunt-contrib-*` plugins use `grunt-contrib-internal` to construct the `README.md` and `CONTRIBUTING.md` files. The source files are located in the corresponding `docs/` folder.

So, please edit the source files rather than the README directly.

Your changes can be summarized in the following steps:
1. The introduction should be added in top of the file `docs/qunit-overview.md` alongside the other changes about configuring the task and the installation of `PhantomJS`.
2. The options updates should happen in the file `docs/qunit-options.md`, but please don't change the type of `httpBase` to `Boolean`. In fact, it should be a `String` and the default value should be changed to empty string `""`, which I will do after merging this PR.
3. Run `grunt` to generate the new `README.md` file and commit all files

Thanks.

--- 
**_Note_**:
If your editor removes trilling white spaces from markdown files (especially the ones we use to separate at the end of the type of every option, then replace them with `<br>`.

**Comment by mfrasca** [comment]
ok. seen. will make time to contribute my edits the way you indicate. :-)

**Comment by Arkni** [comment]
I removed one unrelated paragraph (the one about coveralls) and squashed the commits.

Thanks!

**Pull request merged**
